/*Student Name: Cynthia Maroupas Student ID : 261119382*/
//This is a program that simulates a virtual hotel. The user can create a hotel with different types of rooms and features.
// The user can also reserve rooms and see the hotel revenue. As requested, I included every class in one Java file to facilitate the testing.

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

// Main class that represents the hotel maker
public class HotelMaker {
    private String name;
    private List<Room> rooms;  // List of all rooms in the hotel

    public HotelMaker(String name) {
        this.name = name;
        this.rooms = new ArrayList<>(); // Initialize the list of rooms
    }

    // Add a room to the hotel
    public void addRoom(Room room) {
        rooms.add(room);
    }

    // Reserve a room of a specific type
    public boolean reserveRoom(RoomType roomType) {
        for (Room room : rooms) {
            if (!room.getReservationStatus() && room.reserveTheRoom(roomType)) {
                return true;
            }
        }
        return false;
    }

    // Get the total revenue generated by the hotel
    public int getRevenue() {
        int revenue = 0;
        for (Room room : rooms) {
            if (room.getReservationStatus()) {
                revenue += room.getPrice();
            }
        }
        return revenue;
    }

    // Main method that runs the program
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        // Get hotel name
        System.out.print("Please enter the name for your Hotel: ");
        String hotelName = scanner.nextLine();
        HotelMaker hotel = new HotelMaker(hotelName);

        // Add rooms and features
        boolean doneAddingRooms = false;
        while (!doneAddingRooms) {
            System.out.println("Welcome to " + hotelName + " Hotel Maker, please select the room you would like to have in your Hotel.");
            System.out.println("1: Single Room $50");
            System.out.println("2: Double Room $80");
            System.out.println("3: Deluxe Room $100");
            System.out.println("4: Done, go to reservation");

            int roomChoice = scanner.nextInt();
            Room room = null;
            switch (roomChoice) {
                case 1:
                    room = new SingleRoom(); // Create a new SingleRoom object
                    break;
                case 2:
                    room = new DoubleRoom(); // Create a new DoubleRoom object
                    break;
                case 3:
                    room = new DeluxeRoom(); // Create a new DeluxeRoom object
                    break;
                case 4:
                    doneAddingRooms = true; // Exit the loop
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
                    continue;
            }

            if (room != null) {
                boolean doneAddingFeatures = false;
                while (!doneAddingFeatures) {
                    System.out.println("What feature does the room have?");
                    System.out.println("1: With view $50");
                    System.out.println("2: With Netflix access $20");
                    System.out.println("3: No special features");
                    System.out.println("4: Done");

                    int featureChoice = scanner.nextInt();
                    switch (featureChoice) {
                        case 1:
                            room = new WithView(room); // Decorate the room with a view
                            break;
                        case 2:
                            room = new WithNetflixAccess(room); // Decorate the room with Netflix access
                            break;
                        case 3:
                            break;
                        case 4:
                            doneAddingFeatures = true; // Exit the loop
                            break;
                        default:
                            System.out.println("Invalid choice. Please try again.");
                            continue;
                    }
                }
                hotel.addRoom(room); // Add the decorated room to the hotel
            }
        }

        // Reserve rooms
        boolean doneReservingRooms = false;
        while (!doneReservingRooms) {
            System.out.println("Hi customer, what room would you like?:");
            System.out.println("1: Single Room");
            System.out.println("2: Double Room");
            System.out.println("3: Deluxe Room");
            System.out.println("4: Done, show the Hotel revenue");

            int reservationChoice = scanner.nextInt();
            RoomType roomType = null;
            switch (reservationChoice) {
                case 1:
                    roomType = RoomType.SINGLE;
                    break;
                case 2:
                    roomType = RoomType.DOUBLE;
                    break;
                case 3:
                    roomType = RoomType.DELUXE;
                    break;
                case 4:
                    doneReservingRooms = true;
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
                    continue;
            }
            if (roomType != null) {
                if (hotel.reserveRoom(roomType)) {
                    System.out.println("Reservation successful");
                } else {
                    System.out.println("That room is not available");
                }
            }
            // Print current rooms status
            System.out.println("Current rooms status: ");
            for (Room room : hotel.rooms) {
                System.out.println("Type=" + room.getDescription() + ", Price=" + room.getPrice() + ", isReserved?=" + room.getReservationStatus());
            }
        }

        // Display hotel revenue
        System.out.println("Hotel revenue: " + hotel.getRevenue());
    }
}

// An enumeration of the available room types in the hotel: SINGLE, DOUBLE, and DELUXE.
enum RoomType {
    SINGLE, DOUBLE, DELUXE;
}
/**
 The Room interface defines the methods that all room types must implement.
 getPrice() returns the price of the room.
 getDescription() returns the description of the room.
 getReservationStatus() returns whether the room is reserved or not.
 reserveTheRoom() reserves the room with the given RoomType.
 */
interface Room {
    int getPrice();

    String getDescription();

    boolean getReservationStatus();

    boolean reserveTheRoom(RoomType roomType);
}

/**
 Implementation of the Room interface for a Single Room.
 */
class SingleRoom implements Room {
    private int price = 50;
    private String description = "Single Room";
    private boolean isReserved = false;

    /**

     Returns the price of the room.
     @return the price of the room
     */
    public int getPrice() {
        return price;
    }
    /**

     Returns the description of the room.
     @return the description of the room
     */
    public String getDescription() {
        return description;
    }
    /**

     Returns the reservation status of the room.
     @return the reservation status of the room
     */
    public boolean getReservationStatus() {
        return isReserved;
    }
    /**

     Reserves the room if it is not already reserved and if the room type is SINGLE.
     @param roomType the room type requested
     @return true if the room is reserved, false otherwise
     */
    public boolean reserveTheRoom(RoomType roomType) {
        if (roomType == RoomType.SINGLE) {
            if (!isReserved) {
                isReserved = true;
                return true;
            }
        }
        return false;
    }
}
// Concrete implementation of Room interface for Double Room
class DoubleRoom implements Room {
    private int price = 80;
    private String description = "Double Room";
    private boolean isReserved = false;

    public int getPrice() {
        return price;
    }

    public String getDescription() {
        return description;
    }

    public boolean getReservationStatus() {
        return isReserved;
    }

    public boolean reserveTheRoom(RoomType roomType) {
        if (roomType == RoomType.DOUBLE) {
            if (!isReserved) {
                isReserved = true;
                return true;
            }
        }
        return false;
    }
}
// Concrete implementation of Room interface for Deluxe Room
class DeluxeRoom implements Room {
    private int price = 100;
    private String description = "Deluxe Room";
    private boolean isReserved = false;

    public int getPrice() {
        return price;
    }

    public String getDescription() {
        return description;
    }

    public boolean getReservationStatus() {
        return isReserved;
    }

    public boolean reserveTheRoom(RoomType roomType) {
        if (roomType == RoomType.DELUXE) {
            if (!isReserved) {
                isReserved = true;
                return true;
            }
        }
        return false;
    }
}
// Abstract class for room decorators
abstract class RoomDecorator implements Room {
    protected Room room;

    public RoomDecorator(Room room) {
        this.room = room;
    }

    public int getPrice() {
        return room.getPrice();
    }

    public String getDescription() {
        return room.getDescription();
    }

    public boolean getReservationStatus() {
        return room.getReservationStatus();
    }

    public boolean reserveTheRoom(RoomType roomType) {
        return room.reserveTheRoom(roomType);
    }
}
// Concrete decorator class for adding a view to a room
class WithView extends RoomDecorator {
    private int price = 50;

    public WithView(Room room) {
        super(room);
    }

    public int getPrice() {
        return super.getPrice() + price;
    }

    public String getDescription() {
        return super.getDescription() + " + With view";
    }
}
// Concrete decorator class for adding Netflix access to a room
class WithNetflixAccess extends RoomDecorator {
    private int price = 20;

    public WithNetflixAccess(Room room) {
        super(room);
    }

    public int getPrice() {
        return super.getPrice() + price;
    }

    public String getDescription() {
        return super.getDescription() + " + With Netflix access";
    }
}